[input]
# (Optional) Name of this job. Output names are superseded by this variable.
# Leave empty (e.g. "") if you'd like to keep the tower data file name as the outputs' name prefix.
name                    = "LettuceS2"

# Path to input file.
file                    = "./data/MB_LET_S2_pi_qc_20250317.csv"
# Latitude and longitude of tower location.
location                = [36.4568849031, -121.382712914]

# Weight by reference ETo, must be true or false.
# Multiplies overlap counts by fraction of cummulative ETo for each day.
weigh_by_eto           = false
# Reference ET data input. Ignored if `weigh_by_eto` is `false`.
eto_file                = "./data/LETTUCE2024_fluxdataqaqc_20250317.csv"

# Estimated height of the boundary layer in meters.
boundary_layer_height   = 2000
# Percentage of source area for which to provide contours, must be between 10% and 90%. 
# Must be a single value in a list. Multiple values may be provided, but only the first will be used.
# Expressed either in percentages ("80") or as fractions of 1 ("0.8"). 
source_contour_ratio    = [90]

[output]
# Path to output directory.
output_dir              = "./results/"
# Meters per pixel for the output image.
spatial_resolution      = 1
# Overlap threshold for polygonization.
overlap_threshold       = 0.2
# If the output results in disjointed polygons, use best-effort approach to combine them into one.
coverage_union = false

[graphs]
# Whether to export a heatmap showing accumulated overlaps.
heatmap = false
# Whether to export a chart showing the footprint polygon.
polygon = true