[input]
# Path to input file.
file                    = "./data/MB_LET_S2_pi_qc_20250317.csv"
# Latitude and longitude of tower location.
location                = [36.456667, -121.382222]

# Weight by reference ETo
weigh_by_eto           = false
# Reference ET data input. Ignored if `weigh_by_eto` is `false`.
eto_file                = "./data/LETTUCE2024_fluxdataqaqc_20250317.csv"

# Estimated height of the boundary layer in meters.
boundary_layer_height   = 2000
# Percentage of source area for which to provide contours, must be between 10% and 90%. 
# Can be either a single value (e.g., "80") or a list of values (e.g., "[10, 20, 30]")
# Expressed either in percentages ("80") or as fractions of 1 ("0.8"). 
source_contour_ratio    = [90]

# Maximum number of rows to read from the input file (-1 to include all).
max_rows                = -1

[output]
# Path to output directory.
output_dir              = "./"
# Meters per pixel for the output image.
spatial_resolution      = 1
# Overlap threshold for polygonization.
overlap_threshold       = 0.8
